# Generated by Django 4.2.5 on 2024-01-28 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_api', '0005_remove_comment_blog_remove_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('waiting_for_approval', 'Waiting for Approval'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('deleted', 'Deleted'), ('reported', 'Reported')], default='confirmed', max_length=20)),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog_api.blog')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments_api.comment')),
            ],
        ),
    ]
