# Generated by Django 4.2.5 on 2024-01-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_api', '0005_remove_comment_blog_remove_comment_parent_comment_and_more'),
        ('comments_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullName', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('profilePic', models.URLField(blank=True, null=True)),
                ('roles', models.CharField(blank=True, choices=[('User', 'User'), ('Content-Creator', 'Content-Creator'), ('Admin', 'Admin'), ('Moderator', 'Moderator')], default='User', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('Blog', models.ManyToManyField(blank=True, related_name='users', to='blog_api.blog')),
                ('comments', models.ManyToManyField(blank=True, related_name='users', to='comments_api.comment')),
                ('savedblog', models.ManyToManyField(blank=True, related_name='saved_users', to='blog_api.blog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
