# Generated by Django 4.2.5 on 2024-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=250)),
                ('Body', models.JSONField()),
                ('Url', models.CharField(max_length=255, unique=True)),
                ('Status', models.JSONField(choices=[('public', 'Public'), ('draft', 'Draft'), ('private', 'Private'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('hold-for-validation', 'Hold for Validation')], default=list)),
                ('Thumbnail', models.URLField(default='https://image.com')),
                ('Likes', models.JSONField(blank=True, default=dict)),
                ('Views', models.IntegerField(default=0)),
                ('Tags', models.JSONField(blank=True, default=list)),
                ('Comments', models.JSONField(default=list)),
                ('User', models.CharField(max_length=100)),
                ('Category', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
