# Generated by Django 4.2.5 on 2024-01-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_remove_blog_id_blog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Views',
            new_name='views',
        ),
    ]
