# Generated by Django 4.2.5 on 2024-01-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_comment_alter_blog_id_customuser_comment_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='savedblog',
        ),
    ]
